id = "plc-structured-text"
name = "PLC Structured Text"
version = "0.0.3"
schema_version = 1
authors = ["Artur Khalikov <arthurka.x.r@gmail.com>"]
description = "Structured Text Zed extension"
repository = "https://github.com/ArthurkaX/zed-plc-structured-text"
languages = ["languages/structured-text"]

[grammars.structured_text]
repository = "https://github.com/ArthurkaX/tree-sitter-structured-text.git"
rev = "e01eab6de143d64aa6924ca083f3c41079ab26f9"
