id = "plc-structured-text"
name = "PLC Structured Text"
version = "0.0.3"
schema_version = 1
authors = ["ArthurkaX"]
description = "Structured Text language support for Zed"
repository = "https://github.com/ArthurkaX/zed-plc-structured-text"

[grammars.structured_text]
repository = "file:///C:/Workspace/Active/tree-sitter-structured-text"
rev = "e01eab6de143d64aa6924ca083f3c41079ab26f9"
